package LDI.Empleados;


/**
* Empleados/EmpleadoPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Empleados.idl
* lunes 12 de noviembre de 2018 17H14' COT
*/

public abstract class EmpleadoPOA extends org.omg.PortableServer.Servant
 implements LDI.Empleados.EmpleadoOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarEmpleado", new java.lang.Integer (0));
    _methods.put ("actualizarEmpleado", new java.lang.Integer (1));
    _methods.put ("eliminarEmpleado", new java.lang.Integer (2));
    _methods.put ("consultarEmpleado", new java.lang.Integer (3));
    _methods.put ("shutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Empleados/Empleado/insertarEmpleado
       {
         int identificacion = in.read_long ();
         String nombre = in.read_wstring ();
         int idDepartamento = in.read_long ();
         int idCiudad = in.read_long ();
         String direcion = in.read_wstring ();
         String correo = in.read_wstring ();
         String telefono = in.read_wstring ();
         char estado = in.read_wchar ();
         String urlImagen = in.read_wstring ();
         byte imagen = in.read_octet ();
         boolean $result = false;
         $result = this.insertarEmpleado (identificacion, nombre, idDepartamento, idCiudad, direcion, correo, telefono, estado, urlImagen, imagen);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // Empleados/Empleado/actualizarEmpleado
       {
         int identificacion = in.read_long ();
         String nombre = in.read_wstring ();
         int idDepartamento = in.read_long ();
         int idCiudad = in.read_long ();
         String direcion = in.read_wstring ();
         String correo = in.read_wstring ();
         String telefono = in.read_wstring ();
         char estado = in.read_wchar ();
         String urlImagen = in.read_wstring ();
         byte imagen = in.read_octet ();
         boolean $result = false;
         $result = this.actualizarEmpleado (identificacion, nombre, idDepartamento, idCiudad, direcion, correo, telefono, estado, urlImagen, imagen);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Empleados/Empleado/eliminarEmpleado
       {
         int identificacion = in.read_long ();
         boolean $result = false;
         $result = this.eliminarEmpleado (identificacion);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // Empleados/Empleado/consultarEmpleado
       {
         int identificacion = in.read_long ();
         String $result = null;
         $result = this.consultarEmpleado (identificacion);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 4:  // Empleados/Empleado/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Empleados/Empleado:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Empleado _this() 
  {
    return EmpleadoHelper.narrow(
    super._this_object());
  }

  public Empleado _this(org.omg.CORBA.ORB orb) 
  {
    return EmpleadoHelper.narrow(
    super._this_object(orb));
  }


} // class EmpleadoPOA
