package LDI.Empleados;

/**
* Empleados/EmpleadoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Empleados.idl
* lunes 12 de noviembre de 2018 17H14' COT
*/

public final class EmpleadoHolder implements org.omg.CORBA.portable.Streamable
{
  public LDI.Empleados.Empleado value = null;

  public EmpleadoHolder ()
  {
  }

  public EmpleadoHolder (LDI.Empleados.Empleado initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LDI.Empleados.EmpleadoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LDI.Empleados.EmpleadoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LDI.Empleados.EmpleadoHelper.type ();
  }

}
