package LDI.Proveedores;


/**
* Proveedores/Proveedor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Proveedores.idl
* domingo 11 de noviembre de 2018 20H15' COT
*/

public interface Proveedor extends ProveedorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Proveedor
