package Credenciales;

/**
* Credenciales/CredencialHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Credenciales.idl
* domingo 28 de octubre de 2018 17H54' COT
*/

public final class CredencialHolder implements org.omg.CORBA.portable.Streamable
{
  public Credenciales.Credencial value = null;

  public CredencialHolder ()
  {
  }

  public CredencialHolder (Credenciales.Credencial initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Credenciales.CredencialHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Credenciales.CredencialHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Credenciales.CredencialHelper.type ();
  }

}
