package Credenciales;


/**
* Credenciales/CredencialPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Credenciales.idl
* domingo 28 de octubre de 2018 17H54' COT
*/

public abstract class CredencialPOA extends org.omg.PortableServer.Servant
 implements Credenciales.CredencialOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarCredencial", new java.lang.Integer (0));
    _methods.put ("actualizarCredencial", new java.lang.Integer (1));
    _methods.put ("eliminarCredencial", new java.lang.Integer (2));
    _methods.put ("consultarCredencial", new java.lang.Integer (3));
    _methods.put ("shutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Credenciales/Credencial/insertarCredencial
       {
         int codigo = in.read_long ();
         String user = in.read_wstring ();
         String password = in.read_wstring ();
         char estado = in.read_wchar ();
         boolean $result = false;
         $result = this.insertarCredencial (codigo, user, password, estado);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // Credenciales/Credencial/actualizarCredencial
       {
         int codigo = in.read_long ();
         String user = in.read_wstring ();
         String password = in.read_wstring ();
         char estado = in.read_wchar ();
         boolean $result = false;
         $result = this.actualizarCredencial (codigo, user, password, estado);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Credenciales/Credencial/eliminarCredencial
       {
         int codigo = in.read_long ();
         boolean $result = false;
         $result = this.eliminarCredencial (codigo);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // Credenciales/Credencial/consultarCredencial
       {
         int codigo = in.read_long ();
         String $result = null;
         $result = this.consultarCredencial (codigo);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 4:  // Credenciales/Credencial/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Credenciales/Credencial:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Credencial _this() 
  {
    return CredencialHelper.narrow(
    super._this_object());
  }

  public Credencial _this(org.omg.CORBA.ORB orb) 
  {
    return CredencialHelper.narrow(
    super._this_object(orb));
  }


} // class CredencialPOA
