package Credenciales;


/**
* Credenciales/CredencialOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Credenciales.idl
* domingo 28 de octubre de 2018 17H54' COT
*/

public interface CredencialOperations 
{
  boolean insertarCredencial (int codigo, String user, String password, char estado);
  boolean actualizarCredencial (int codigo, String user, String password, char estado);
  boolean eliminarCredencial (int codigo);
  String consultarCredencial (int codigo);
  void shutdown ();
} // interface CredencialOperations
