package LDI.Credenciales;


/**
* Credenciales/CredencialHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Credenciales.idl
* domingo 28 de octubre de 2018 17H54' COT
*/

abstract public class CredencialHelper
{
  private static String  _id = "IDL:Credenciales/Credencial:1.0";

  public static void insert (org.omg.CORBA.Any a, LDI.Credenciales.Credencial that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static LDI.Credenciales.Credencial extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (LDI.Credenciales.CredencialHelper.id (), "Credencial");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static LDI.Credenciales.Credencial read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CredencialStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, LDI.Credenciales.Credencial value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static LDI.Credenciales.Credencial narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof LDI.Credenciales.Credencial)
      return (LDI.Credenciales.Credencial)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      LDI.Credenciales._CredencialStub stub = new LDI.Credenciales._CredencialStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static LDI.Credenciales.Credencial unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof LDI.Credenciales.Credencial)
      return (LDI.Credenciales.Credencial)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      LDI.Credenciales._CredencialStub stub = new LDI.Credenciales._CredencialStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
