package LDI.Credenciales;


/**
* Credenciales/Credencial.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Credenciales.idl
* domingo 28 de octubre de 2018 17H54' COT
*/

public interface Credencial extends CredencialOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Credencial
