/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import AppPackage.AnimationClass;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ruben
 */
public class MenuAdministrador extends javax.swing.JInternalFrame {

    //Variables globales.
 
    public MenuAdministrador() {
        initComponents();
        //jdkEscritorioAdmin.setBorder(new ImagenFondo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMenuAdministrador = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        btnMedicamento = new javax.swing.JButton();
        btnProveedor = new javax.swing.JButton();
        btnEmpleado = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        btnCredencial = new javax.swing.JButton();
        jdkEscritorioAdmin = new javax.swing.JDesktopPane();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpMenuAdministrador.setBackground(new java.awt.Color(255, 255, 255));
        jpMenuAdministrador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jpMenuAdministrador.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 760, 10));

        btnMedicamento.setBackground(new java.awt.Color(0, 0, 0));
        btnMedicamento.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        btnMedicamento.setForeground(new java.awt.Color(0, 0, 0));
        btnMedicamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Medicamentos.png"))); // NOI18N
        btnMedicamento.setText("Medicamentos");
        btnMedicamento.setBorder(null);
        btnMedicamento.setBorderPainted(false);
        btnMedicamento.setContentAreaFilled(false);
        btnMedicamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMedicamento.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Medicamento2.png"))); // NOI18N
        btnMedicamento.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Medicamento2.png"))); // NOI18N
        btnMedicamento.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Medicamentos.png"))); // NOI18N
        btnMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicamentoActionPerformed(evt);
            }
        });
        jpMenuAdministrador.add(btnMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnProveedor.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        btnProveedor.setForeground(new java.awt.Color(0, 0, 0));
        btnProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Proveedores.png"))); // NOI18N
        btnProveedor.setText("Proveedores");
        btnProveedor.setBorder(null);
        btnProveedor.setBorderPainted(false);
        btnProveedor.setContentAreaFilled(false);
        btnProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProveedor.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Proveedores2.png"))); // NOI18N
        btnProveedor.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Proveedores2.png"))); // NOI18N
        btnProveedor.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Proveedores.png"))); // NOI18N
        btnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorActionPerformed(evt);
            }
        });
        jpMenuAdministrador.add(btnProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        btnEmpleado.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        btnEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        btnEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Empleados.png"))); // NOI18N
        btnEmpleado.setText("Empleados");
        btnEmpleado.setBorder(null);
        btnEmpleado.setBorderPainted(false);
        btnEmpleado.setContentAreaFilled(false);
        btnEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmpleado.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Empleados2.png"))); // NOI18N
        btnEmpleado.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Empleados2.png"))); // NOI18N
        btnEmpleado.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Empleados.png"))); // NOI18N
        btnEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadoActionPerformed(evt);
            }
        });
        jpMenuAdministrador.add(btnEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        btnPerfil.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        btnPerfil.setForeground(new java.awt.Color(0, 0, 0));
        btnPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Perfil.png"))); // NOI18N
        btnPerfil.setText("Perfil");
        btnPerfil.setBorder(null);
        btnPerfil.setBorderPainted(false);
        btnPerfil.setContentAreaFilled(false);
        btnPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPerfil.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Perfil2.png"))); // NOI18N
        btnPerfil.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Perfil2.png"))); // NOI18N
        btnPerfil.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Perfil.png"))); // NOI18N
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });
        jpMenuAdministrador.add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, -1, -1));

        btnCredencial.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        btnCredencial.setForeground(new java.awt.Color(0, 0, 0));
        btnCredencial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Credenciales.png"))); // NOI18N
        btnCredencial.setText("Credenciales");
        btnCredencial.setBorder(null);
        btnCredencial.setBorderPainted(false);
        btnCredencial.setContentAreaFilled(false);
        btnCredencial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCredencial.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Credenciales2.png"))); // NOI18N
        btnCredencial.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Credenciales2.png"))); // NOI18N
        btnCredencial.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Credenciales.png"))); // NOI18N
        btnCredencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCredencialActionPerformed(evt);
            }
        });
        jpMenuAdministrador.add(btnCredencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        getContentPane().add(jpMenuAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 80));
        getContentPane().add(jdkEscritorioAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 760, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicamentoActionPerformed
        //Se realiza una instanciación sobre la clase RegistroVendedore para obtener todos los métodos.

        Medicamento mostrarVentanaMedicamento = new Medicamento();
        //Se ancla el JinternalFrame que anteriormente se creó (se llama RegistroProveedore)
        this.jdkEscritorioAdmin.add(mostrarVentanaMedicamento);
        /* ***Se emplea un try para ejecutar satisfactoriamente el maximizar en el area de Desktop Pane(Componente de Java Swing).
        ***Si sucede alguna eventualidad(error) entraría al catch y posteriormente dirá el error presentado */
        try {
            mostrarVentanaMedicamento.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Muestra la ventana dentro de la aplicación.
        mostrarVentanaMedicamento.setVisible(true);
        
        
       
    }//GEN-LAST:event_btnMedicamentoActionPerformed

    private void btnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorActionPerformed
        
        //Se realiza una instanciación sobre la clase Proveedor para obtener todos los métodos, atributos.

        Proveedor mostrarVentanaProveedor = new Proveedor();
        //Se ancla el JinternalFrame que anteriormente se creó (se llama Proveedor)
        this.jdkEscritorioAdmin.add(mostrarVentanaProveedor);
        /* ***Se emplea un try para ejecutar satisfactoriamente el maximizar en el area de Desktop Pane(Componente de Java Swing).
        ***Si sucede alguna eventualidad(error) entraría al catch y posteriormente dirá el error presentado */
        try {
            mostrarVentanaProveedor.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Muestra la ventana dentro de la aplicación.
        mostrarVentanaProveedor.setVisible(true);
        
        
        
        
    }//GEN-LAST:event_btnProveedorActionPerformed

    private void btnEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadoActionPerformed
        //Se realiza una instanciación sobre la clase RegistroVendedore para obtener todos los métodos.

        Empleado mostrarVentanaEmpleado = new Empleado();
        //Se ancla el JinternalFrame que anteriormente se creó (se llama RegistroProveedore)
        this.jdkEscritorioAdmin.add(mostrarVentanaEmpleado);
        /* ***Se emplea un try para ejecutar satisfactoriamente el maximizar en el area de Desktop Pane(Componente de Java Swing).
        ***Si sucede alguna eventualidad(error) entraría al catch y posteriormente dirá el error presentado */
        try {
            mostrarVentanaEmpleado.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Muestra la ventana dentro de la aplicación.
        mostrarVentanaEmpleado.setVisible(true);
    }//GEN-LAST:event_btnEmpleadoActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        //Se realiza una instanciación sobre la clase RegistroVendedore para obtener todos los métodos.

        Perfil mostrarVentanaPerfil = new Perfil();
        //Se ancla el JinternalFrame que anteriormente se creó (se llama RegistroProveedore)
        this.jdkEscritorioAdmin.add(mostrarVentanaPerfil);
        /* ***Se emplea un try para ejecutar satisfactoriamente el maximizar en el area de Desktop Pane(Componente de Java Swing).
        ***Si sucede alguna eventualidad(error) entraría al catch y posteriormente dirá el error presentado */
        try {
            mostrarVentanaPerfil.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Muestra la ventana dentro de la aplicación.
        mostrarVentanaPerfil.setVisible(true);
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnCredencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCredencialActionPerformed
        //Se realiza una instanciación sobre la clase RegistroVendedore para obtener todos los métodos.

        Credencial mostrarVentanaCredencial = new Credencial();
        //Se ancla el JinternalFrame que anteriormente se creó (se llama RegistroProveedore)
        this.jdkEscritorioAdmin.add(mostrarVentanaCredencial);
        /* ***Se emplea un try para ejecutar satisfactoriamente el maximizar en el area de Desktop Pane(Componente de Java Swing).
        ***Si sucede alguna eventualidad(error) entraría al catch y posteriormente dirá el error presentado */
        try {
            mostrarVentanaCredencial.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Muestra la ventana dentro de la aplicación.
        mostrarVentanaCredencial.setVisible(true);
    }//GEN-LAST:event_btnCredencialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCredencial;
    private javax.swing.JButton btnEmpleado;
    private javax.swing.JButton btnMedicamento;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnProveedor;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JDesktopPane jdkEscritorioAdmin;
    private javax.swing.JPanel jpMenuAdministrador;
    // End of variables declaration//GEN-END:variables
}
