/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import AppPackage.AnimationClass;

/**
 *
 * @author Ruben
 */
public class Perfil extends javax.swing.JInternalFrame {

    /**
     * Creates new form Perfil
     */
    public Perfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDato = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txtNombreLaboratorio = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        lblNombreLaboratorio = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblGuardar = new javax.swing.JLabel();
        lblGuardar1 = new javax.swing.JLabel();
        lblGuardar3 = new javax.swing.JLabel();
        lblGuardar4 = new javax.swing.JLabel();
        lblDato1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        txtNombreLaboratorio1 = new javax.swing.JTextField();
        lblNombreLaboratorio1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTelefono1 = new javax.swing.JTextField();
        lblTelefono1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblTelefono2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDato.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        lblDato.setForeground(new java.awt.Color(0, 0, 0));
        lblDato.setText("Datos");
        getContentPane().add(lblDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 320, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 30, 10));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 10, 360));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 250, 10));

        txtNombreLaboratorio.setBackground(new java.awt.Color(214, 217, 223));
        txtNombreLaboratorio.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        txtNombreLaboratorio.setForeground(new java.awt.Color(51, 51, 255));
        txtNombreLaboratorio.setBorder(null);
        getContentPane().add(txtNombreLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 120, 20));

        txtTelefono.setBackground(new java.awt.Color(214, 217, 223));
        txtTelefono.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(51, 51, 255));
        txtTelefono.setBorder(null);
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 120, 20));

        lblNombreLaboratorio.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        lblNombreLaboratorio.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreLaboratorio.setText("Nombre:");
        getContentPane().add(lblNombreLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 30));

        lblTelefono.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(0, 0, 0));
        lblTelefono.setText("Telefono:");
        getContentPane().add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Capturkla.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 120, 3));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Capturkla.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 120, 4));

        lblDireccion.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(0, 0, 0));
        lblDireccion.setText("Dirección:");
        getContentPane().add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 30));

        txtDireccion.setBackground(new java.awt.Color(214, 217, 223));
        txtDireccion.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(51, 51, 255));
        txtDireccion.setBorder(null);
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 120, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Capturkla.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 120, 4));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoGuardar.png"))); // NOI18N
        btnGuardar.setBorder(null);
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoGuardar2.png"))); // NOI18N
        btnGuardar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoGuardar2.png"))); // NOI18N
        btnGuardar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoGuardar.png"))); // NOI18N
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actualizar.png"))); // NOI18N
        btnActualizar.setBorder(null);
        btnActualizar.setBorderPainted(false);
        btnActualizar.setContentAreaFilled(false);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actualizar2.png"))); // NOI18N
        btnActualizar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actualizar2.png"))); // NOI18N
        btnActualizar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actualizar.png"))); // NOI18N
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminar.png"))); // NOI18N
        btnEliminar.setBorder(null);
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminar2.png"))); // NOI18N
        btnEliminar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminar2.png"))); // NOI18N
        btnEliminar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminar.png"))); // NOI18N
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, -1, -1));

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar.png"))); // NOI18N
        btnLimpiar.setBorder(null);
        btnLimpiar.setBorderPainted(false);
        btnLimpiar.setContentAreaFilled(false);
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar2.png"))); // NOI18N
        btnLimpiar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar2.png"))); // NOI18N
        btnLimpiar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar.png"))); // NOI18N
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, -1, -1));

        lblGuardar.setBackground(new java.awt.Color(0, 0, 0));
        lblGuardar.setFont(new java.awt.Font("Decker", 1, 12)); // NOI18N
        lblGuardar.setForeground(new java.awt.Color(0, 0, 0));
        lblGuardar.setText("Limpiar");
        getContentPane().add(lblGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, -1, -1));

        lblGuardar1.setBackground(new java.awt.Color(0, 0, 0));
        lblGuardar1.setFont(new java.awt.Font("Decker", 1, 12)); // NOI18N
        lblGuardar1.setForeground(new java.awt.Color(0, 0, 0));
        lblGuardar1.setText("Guardar");
        getContentPane().add(lblGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));

        lblGuardar3.setBackground(new java.awt.Color(0, 0, 0));
        lblGuardar3.setFont(new java.awt.Font("Decker", 1, 12)); // NOI18N
        lblGuardar3.setForeground(new java.awt.Color(0, 0, 0));
        lblGuardar3.setText("Actualizar");
        getContentPane().add(lblGuardar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, -1, -1));

        lblGuardar4.setBackground(new java.awt.Color(0, 0, 0));
        lblGuardar4.setFont(new java.awt.Font("Decker", 1, 12)); // NOI18N
        lblGuardar4.setForeground(new java.awt.Color(0, 0, 0));
        lblGuardar4.setText("Eliminar");
        getContentPane().add(lblGuardar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, -1, -1));

        lblDato1.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        lblDato1.setForeground(new java.awt.Color(0, 0, 0));
        lblDato1.setText("Foto");
        getContentPane().add(lblDato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 40, -1));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 30, 10));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 22, 10, 140));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 10, 140));
        getContentPane().add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 140, 10));
        getContentPane().add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 80, 10));

        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 10, 360));

        txtNombreLaboratorio1.setBackground(new java.awt.Color(214, 217, 223));
        txtNombreLaboratorio1.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        txtNombreLaboratorio1.setForeground(new java.awt.Color(51, 51, 255));
        txtNombreLaboratorio1.setBorder(null);
        getContentPane().add(txtNombreLaboratorio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 120, 20));

        lblNombreLaboratorio1.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        lblNombreLaboratorio1.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreLaboratorio1.setText("Identificación:");
        getContentPane().add(lblNombreLaboratorio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Capturkla.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 120, 3));

        txtTelefono1.setBackground(new java.awt.Color(214, 217, 223));
        txtTelefono1.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        txtTelefono1.setForeground(new java.awt.Color(51, 51, 255));
        txtTelefono1.setBorder(null);
        getContentPane().add(txtTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 120, 20));

        lblTelefono1.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        lblTelefono1.setForeground(new java.awt.Color(0, 0, 0));
        lblTelefono1.setText("Foto:");
        getContentPane().add(lblTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Capturkla.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 120, 4));

        lblTelefono2.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        lblTelefono2.setForeground(new java.awt.Color(0, 0, 0));
        lblTelefono2.setText("Contraseña:");
        getContentPane().add(lblTelefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 20));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Marco.png"))); // NOI18N
        jButton1.setToolTipText("Añadir Foto");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setDefaultCapable(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Marco2.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Marco2.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Marco.png"))); // NOI18N
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 40, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblDato;
    private javax.swing.JLabel lblDato1;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblGuardar;
    private javax.swing.JLabel lblGuardar1;
    private javax.swing.JLabel lblGuardar3;
    private javax.swing.JLabel lblGuardar4;
    private javax.swing.JLabel lblNombreLaboratorio;
    private javax.swing.JLabel lblNombreLaboratorio1;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTelefono1;
    private javax.swing.JLabel lblTelefono2;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombreLaboratorio;
    private javax.swing.JTextField txtNombreLaboratorio1;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefono1;
    // End of variables declaration//GEN-END:variables
}
