package Frame;

import AppPackage.AnimationClass;
import LDI.TablaCredencial;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Ruben Dario Scalante & Abdruval Collazos Polania.
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    //Variables globales.
    
    private int posicioX;
    private int posicionY;
    
    //Se realiza una instanciación para que los objetos obtengan todos los metodos de esa libreria(ImageIcon)
    ImageIcon imagenAviso =  new ImageIcon(getClass().getResource("/Imagenes/WarningAviso.png"));
    
    
    public VentanaPrincipal() {
        initComponents();
        
        //Sirve para que la ventana aparezca en el centro.
        this.setLocationRelativeTo(null);
        //Sirve para que la imagen predeterminada de java se pueda cambiar.
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/IconoFarmacia.png")).getImage()); 
    }

    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpIngreso = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        lblSalirr = new javax.swing.JLabel();
        lblDesarollador = new javax.swing.JLabel();
        lblAyuda = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        jpBarraSuperior = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        btnMinimizar = new javax.swing.JButton();
        jdkEscritorio = new javax.swing.JDesktopPane();
        lblImagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpIngreso.setBackground(new java.awt.Color(255, 255, 255));
        jpIngreso.setForeground(new java.awt.Color(255, 255, 255));
        jpIngreso.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jpIngresoMouseDragged(evt);
            }
        });
        jpIngreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpIngresoMousePressed(evt);
            }
        });
        jpIngreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(238, 112, 82));
        jLabel1.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 112, 82));
        jLabel1.setText("Password:");
        jpIngreso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        jLabel3.setBackground(new java.awt.Color(238, 112, 82));
        jLabel3.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 112, 82));
        jLabel3.setText("USER:");
        jpIngreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        txtUser.setBackground(new java.awt.Color(255, 255, 255));
        txtUser.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        txtUser.setForeground(new java.awt.Color(153, 153, 153));
        txtUser.setBorder(null);
        jpIngreso.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 160, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jpIngreso.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 312, 190, 10));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenUsuario.png"))); // NOI18N
        jpIngreso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 110, 110));

        txtPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtPassword.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(153, 153, 153));
        txtPassword.setBorder(null);
        jpIngreso.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 157, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jpIngreso.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 190, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_customer_32px_1.png"))); // NOI18N
        jpIngreso.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Key_32px.png"))); // NOI18N
        jpIngreso.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        btnIniciarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Enter_OFF.png"))); // NOI18N
        btnIniciarSesion.setBorder(null);
        btnIniciarSesion.setBorderPainted(false);
        btnIniciarSesion.setContentAreaFilled(false);
        btnIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciarSesion.setRolloverEnabled(true);
        btnIniciarSesion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Enter_ON.png"))); // NOI18N
        btnIniciarSesion.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Enter_ON.png"))); // NOI18N
        btnIniciarSesion.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Enter_ON.png"))); // NOI18N
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        jpIngreso.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 90, 30));

        lblSalirr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Multiply_32px.png"))); // NOI18N
        jpIngreso.add(lblSalirr, new org.netbeans.lib.awtextra.AbsoluteConstraints(-35, 200, -1, 40));

        lblDesarollador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icon_Desarrolladores.png"))); // NOI18N
        jpIngreso.add(lblDesarollador, new org.netbeans.lib.awtextra.AbsoluteConstraints(-35, 150, -1, 40));

        lblAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/help.png"))); // NOI18N
        jpIngreso.add(lblAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(-35, 100, -1, 40));

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Menu_32px.png"))); // NOI18N
        btnMenu.setBorder(null);
        btnMenu.setBorderPainted(false);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu-button-of-three-horizontal-lines.png"))); // NOI18N
        btnMenu.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu-button-of-three-horizontal-lines.png"))); // NOI18N
        btnMenu.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Menu_32px.png"))); // NOI18N
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        jpIngreso.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(jpIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 580));

        jpBarraSuperior.setBackground(new java.awt.Color(255, 255, 255));
        jpBarraSuperior.setForeground(new java.awt.Color(255, 255, 255));
        jpBarraSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jpBarraSuperiorMouseDragged(evt);
            }
        });
        jpBarraSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpBarraSuperiorMousePressed(evt);
            }
        });
        jpBarraSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Multiply_32px.png"))); // NOI18N
        btnSalir.setBorder(null);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setDefaultCapable(false);
        btnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cross-mark-on-a-black-circle-background.png"))); // NOI18N
        btnSalir.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cross-mark-on-a-black-circle-background.png"))); // NOI18N
        btnSalir.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Multiply_32px.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jpBarraSuperior.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, -1, -1));

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        btnMinimizar.setBorder(null);
        btnMinimizar.setBorderPainted(false);
        btnMinimizar.setContentAreaFilled(false);
        btnMinimizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimize.png"))); // NOI18N
        btnMinimizar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimize.png"))); // NOI18N
        btnMinimizar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });
        jpBarraSuperior.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, -1));

        getContentPane().add(jpBarraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 760, 50));

        jdkEscritorio.setBackground(new java.awt.Color(0, 0, 0));

        lblImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/NombreFarmacia.PNG"))); // NOI18N

        jdkEscritorio.setLayer(lblImagenFondo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdkEscritorioLayout = new javax.swing.GroupLayout(jdkEscritorio);
        jdkEscritorio.setLayout(jdkEscritorioLayout);
        jdkEscritorioLayout.setHorizontalGroup(
            jdkEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdkEscritorioLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(lblImagenFondo)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jdkEscritorioLayout.setVerticalGroup(
            jdkEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdkEscritorioLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblImagenFondo)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        getContentPane().add(jdkEscritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 760, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpIngresoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpIngresoMousePressed

        //Se obtine la posición de X,Y cuando el usuario presiona con el Mause.
        posicioX = evt.getX();
        posicionY = evt.getY();
       
        
    }//GEN-LAST:event_jpIngresoMousePressed

    private void jpIngresoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpIngresoMouseDragged
   
        //Finalmente, la ventana se mueve a la posición deseada por el Usuario.
        this.setLocation(this.getLocation().x + evt.getX() - posicioX, this.getLocation().y + evt.getY() - posicionY);
    }//GEN-LAST:event_jpIngresoMouseDragged

    private void jpBarraSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBarraSuperiorMousePressed

        //Se obtine la posición de X,Y cuando el usuario presiona con el Mause.
        posicioX = evt.getX();
        posicionY = evt.getY();
     
    }//GEN-LAST:event_jpBarraSuperiorMousePressed

    private void jpBarraSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBarraSuperiorMouseDragged

        //Finalmente, la ventana se mueve a la posición deseada por el Usuario.
        this.setLocation(this.getLocation().x + evt.getX() - posicioX, this.getLocation().y + evt.getY() - posicionY); 
    }//GEN-LAST:event_jpBarraSuperiorMouseDragged

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        
        //Instanciación de la clase TablaCredencial.
        
        TablaCredencial objCredencial = new  TablaCredencial();
        
        
        //***Validación de cada una de las cajas de Texto***.
        
        //Validar el campo de Identificacion ya sea nit o cédula
        if(txtUser.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor, Digita tú usuario" , "¡Aviso!" , JOptionPane.INFORMATION_MESSAGE , imagenAviso);
            txtUser.requestFocus();
            return;
        }

        //Validar el campo de contraseña para que cumpla con los requerimientos establecidos.
        if (txtPassword.getPassword().length == 0) {
            JOptionPane.showMessageDialog(null, "Por favor, llena el campo de Contraseña" , "¡Aviso!" , JOptionPane.INFORMATION_MESSAGE , imagenAviso);
            txtPassword.requestFocus();
            return;
        }
        
        try {
            
            int codigo =  Integer.parseInt(txtUser.getText());
            String password = String.valueOf(txtPassword.getPassword());
            
            //Se envía la sentencia Sql si el codigo y la contraseña son correctos mostrará la ventana.
            if (objCredencial.verificar("SELECT * FROM credenciales WHERE codigo =" + codigo + "  AND password= " + password) == 1) {

                txtUser.setText("");
                txtPassword.setText("");
                //Se realiza una instanciación sobre la clase RegistroVendedore para obtener todos los métodos.
                MenuAdministrador mostrarVentanaAdministrador = new MenuAdministrador();
                //Se ancla el JinternalFrame que anteriormente se creó (se llama RegistroProveedore)
                this.jdkEscritorio.add(mostrarVentanaAdministrador);
                /* ***Se emplea un try para ejecutar satisfactoriamente el maximizar en el area de Desktop Pane(Componente de Java Swing).
                ***Si sucede alguna eventualidad(error) entraría al catch y posteriormente dirá el error presentado */
                try {
                    mostrarVentanaAdministrador.setMaximum(true);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                //Muestra la ventana dentro de la aplicación.
                mostrarVentanaAdministrador.setVisible(true);
            }
            else {
                JOptionPane.showMessageDialog(null, "¡Lo sentimos! Tú usuario y/o contraseña son incorrectos, ¡intentalo de nuevo!" , "¡Mensaje de Error al sistema!" , JOptionPane.INFORMATION_MESSAGE , imagenAviso); 
                txtUser.setText("");
                txtPassword.setText("");
                txtUser.requestFocus();
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Recuerde, el código es tipo numerico");
            txtUser.setText("");
            txtPassword.setText("");
            txtUser.requestFocus();
        }
        
        

        
  
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        
        //Programación para que el icono del menú, realice el efecto de aparecer las demás opciones.
        
        //Instanciación de la libreria AnimatonClass para cada uno de las opciones (ayuda, desarrolladores, salir)
        
        
        AnimationClass animacionIcono = new AnimationClass();
        
        //******Icono Ayuda******
        //Sirve para que la opción ayuda se visualice al momento de dar click al menu(icono)
        animacionIcono.jLabelXRight(-35, 10, 10, 5, lblAyuda);
        
        //Sirve para que se oculte la opción ayuda al momento de dar click al menu(icono)
        animacionIcono.jLabelXLeft(10, -35, 10, 5, lblAyuda);
        
        //******Icono de desarolladores******
        animacionIcono.jLabelXRight(-35, 10, 10, 5, lblDesarollador);
        
        
        animacionIcono.jLabelXLeft(10, -35, 10, 5, lblDesarollador);
        
        //******Icono de salir******
        animacionIcono.jLabelXRight(-35, 10, 10, 5, lblSalirr);
        
        
        animacionIcono.jLabelXLeft(10, -35, 10, 5, lblSalirr);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        //Programación para el boton salir
        
        int dialog = JOptionPane.YES_NO_OPTION;
        //Almacena la opción que el usuario escoja (1 -> no) (0 -> Si).
        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir?" , "Exit" , dialog);
        
        //Si el usuario presiona Si automaticamente se cierra la ventana.
        if (result == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        //Permite minimizar la ventana.
        this.setState(VentanaPrincipal.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                //Sirve para cambiar la apariencia, anteriormente estaba Nimbus si se desea se puede poner en Windows.
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JDesktopPane jdkEscritorio;
    private javax.swing.JPanel jpBarraSuperior;
    private javax.swing.JPanel jpIngreso;
    private javax.swing.JLabel lblAyuda;
    private javax.swing.JLabel lblDesarollador;
    private javax.swing.JLabel lblImagenFondo;
    private javax.swing.JLabel lblSalirr;
    public static javax.swing.JPasswordField txtPassword;
    public static javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
