package LDI.Medicamentos;


/**
* Medicamentos/_MedicamentoStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Medicamentos.idl
* mi�rcoles 7 de noviembre de 2018 23H15' COT
*/

public class _MedicamentoStub extends org.omg.CORBA.portable.ObjectImpl implements LDI.Medicamentos.Medicamento
{

  public boolean insertarMedicamento (int codigo, String nombre, int idCondicion, int idPresentacion, int ruesLab, int precioVenta, int cantidad, String fechaCaducidad, String ubicacion)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("insertarMedicamento", true);
                $out.write_long (codigo);
                $out.write_wstring (nombre);
                $out.write_long (idCondicion);
                $out.write_long (idPresentacion);
                $out.write_long (ruesLab);
                $out.write_long (precioVenta);
                $out.write_long (cantidad);
                $out.write_wstring (fechaCaducidad);
                $out.write_wstring (ubicacion);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return insertarMedicamento (codigo, nombre, idCondicion, idPresentacion, ruesLab, precioVenta, cantidad, fechaCaducidad, ubicacion        );
            } finally {
                _releaseReply ($in);
            }
  } // insertarMedicamento

  public boolean actualizarMedicamento (int codigo, String nombre, int idCondicion, int idPresentacion, int ruesLab, int precioVenta, int cantidad, String fechaCaducidad, String ubicacion)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("actualizarMedicamento", true);
                $out.write_long (codigo);
                $out.write_wstring (nombre);
                $out.write_long (idCondicion);
                $out.write_long (idPresentacion);
                $out.write_long (ruesLab);
                $out.write_long (precioVenta);
                $out.write_long (cantidad);
                $out.write_wstring (fechaCaducidad);
                $out.write_wstring (ubicacion);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return actualizarMedicamento (codigo, nombre, idCondicion, idPresentacion, ruesLab, precioVenta, cantidad, fechaCaducidad, ubicacion        );
            } finally {
                _releaseReply ($in);
            }
  } // actualizarMedicamento

  public boolean eliminarMedicamento (int codigo, int idCondicion, int idPresentacion, int ruesLab)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("eliminarMedicamento", true);
                $out.write_long (codigo);
                $out.write_long (idCondicion);
                $out.write_long (idPresentacion);
                $out.write_long (ruesLab);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return eliminarMedicamento (codigo, idCondicion, idPresentacion, ruesLab        );
            } finally {
                _releaseReply ($in);
            }
  } // eliminarMedicamento

  public String consultarMedicamento (int codigo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarMedicamento", true);
                $out.write_long (codigo);
                $in = _invoke ($out);
                String $result = $in.read_wstring ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarMedicamento (codigo        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarMedicamento

  public void shutdown ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("shutdown", false);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                shutdown (        );
            } finally {
                _releaseReply ($in);
            }
  } // shutdown

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Medicamentos/Medicamento:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _MedicamentoStub
